title: Todd Williamsen
author: Todd Williamsen
description: Cloud security engineering, Azure architecture, and SOC automation.
url: "https://toddwilliamsen.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
